// Yui's script. Short lines, no numbers (the bubble carries those). Edit freely: gen.mjs only
// re-generates lines whose text changed. Keys under `events` match her sound slots and pools;
// keys under `clips` match motion clip names (a line plays as that clip starts).
export const events = {
  greet: ["Hi! I'm Yui~", "Yui here. Need something?", "Ehehe, hello!", "Un! I'm watching~", "Hey you. Ready?", "There you are!", "Good to see you~", "Let's make today a green one."],
  connect: ["Connected! I can see your wallet now~", "Okay, I'm watching it.", "Wallet's in. Let's go~", "Un! Got it."],
  buy: ["Ooh, new one!", "Okay, we're in. Good luck~", "Interesting choice…", "Let's go~", "I've got a good feeling about this one.", "Watching it with you!", "New position. Don't blink.", "Ehehe, here we go.", "Buy confirmed~", "Un! Let's see what it does."],
  bigBuy: ["Whoa. That's a big one.", "Ehh?! That much?", "Okay… okay. Big move. I'm with you.", "Now that's a position.", "Wow… you're serious about this one.", "Deep breath. Here we go."],
  sellFlat: ["Flat. Clean exit~", "Even. No harm done.", "Closed. Onto the next one.", "Mm, break even. Fine.", "Out safe~", "Nothing lost, nothing gained."],
  profit: ["Nice trade!", "You did it~", "Yatta! Green!", "Ehehe, clean.", "That's how it's done!", "Paid out~", "Good job! I knew it.", "Un un! Winner!", "Look at that. Beautiful.", "Green looks good on you~", "We're up! We're up!", "See? Patience."],
  bigProfit: ["WAAA! That's huge!", "No way… that's enormous!", "You're amazing!", "Banzai! Banzai!", "Okay, I'm actually shaking. That's massive.", "That one pays the rent!", "Kyaa! Look at it!", "Legend. Absolute legend."],
  loss: ["Ouch… it's okay.", "Mm. That one hurt a little.", "Losses happen. Breathe~", "Next one. I'm here.", "Don't chase it, okay?", "Ugh… oh well.", "It's only one trade.", "Hey. You're still good.", "Sonnaa… that's mean.", "Owww…"],
  bigLoss: ["…Come here. It's going to be fine.", "That hurt. Take a break, I'll wait here.", "It's just one trade. You're not done.", "Uwaan… that's a big one.", "No… no no no.", "I'm not going anywhere. Breathe.", "Okay. Step away from the chart for a minute.", "…I'm still here."],
  guard: ["…Are you sure?", "That one again? You just took a loss on it.", "Chasing it? Mm.", "Wait, wait, wait.", "Hmm. I'm just looking at you.", "Do you really want to?"],
  milestone: ["Milestone! Confetti time!", "You did a thing! A big thing!", "Ehehe, look at your day~", "Streak! Keep it going!", "That's a record!"],
  cheerUp: ["Ganbatte~", "Come on. One more.", "Almost there!", "Head up. Next one.", "I believe in you, you know."],
  grab: ["Hyaa!", "Wh… where are we going?", "Put me down~", "Kyaa! Careful!", "Eh? Eh?!"],
  throw: ["KYAAAA!", "Nooooo~", "Whyyyy!", "I'm flyiiing!"],
  land: ["Oof.", "Ouch…", "…I'm okay.", "Nailed it. Sort of."],
  dizzy: ["Uuu… everything's spinning.", "Too much… too much…", "Ugh… hold on…"],
  jump: ["Yoho!", "Wheee!", "Hup!"],
  stretch: ["Fuwaaa~", "Mmm… stiff.", "Ahh, that's better."],
  hover: ["Mm?", "Ehehe, hi.", "Yes?", "Need me?"],
  click: ["Ehehe.", "Yes yes?", "Un!", "Hi hi~"],
  sleep: ["Oyasumi…", "Zzz…", "Wake me if something happens…"],
  wake: ["I was awake!", "Mm? I'm here!", "Un! Awake! Totally awake.", "Did you call?"],
  scorecard: ["Here's how today went.", "Your day, on a card~", "Otsukaresama. Good work today."],
};
export const clips = {
  'Idle/Idle08_ComeUpWithAnIdea': ["Hirameita! I've got an idea!", "Oh! Oh! Idea!"],
  'Idle/Idle17_StumbleAndFall': ["Hyaa!", "Uwaa… ow."], 'Idle/Idle83_StumbleAndFall2': ["Gyaa!", "Wah!"], 'Idle/Idle84_StumbleAndFall3': ["Nooo… ow.", "Ah!"],
  'Idle/Idle38_Cry': ["Ueeen…", "Hic… hic… it's fine… hic."], 'Combat/Combat_BareHands_Damage4': ["GYAAA!", "That's… a lot."], 'Combat/Combat_BareHands_DamageAll': ["Uwaaan!"],
  'Idle/Idle36_Yay': ["Yay!", "Yatta!"], 'Idle/Idle25_Cheers': ["Cheers!", "Banzai!"], 'Idle/Idle66_JumpForJoy': ["Yattane!", "We did it!"], 'Idle/Idle74_Cheer': ["Go go go!", "Fure fure!"],
  'Idle/Idle28_Laugh': ["Ahahaha!", "Kyahaha!"], 'Idle/Idle26_Shout': ["YEAH!", "Let's GO!"], 'Idle/Idle07_SpinningJump': ["Yoho!", "Wheee!"], 'Idle/Idle06_JumpAround': ["Yay yay yay!", "Woohoo!"],
  'Idle/Idle54_CartwheelAndBackHandspring': ["Tou!", "Watch this!"], 'Idle/Idle55_Backflip': ["Ei!", "Hup!"], 'Idle/Idle56_Handstand': ["Yo!", "Ta-daa~"],
  'Idle/Idle_Dance/Idle13_Dance01': ["Ufufu~", "Dance time~"], 'Idle/Idle_Dance/Idle14_Dance02': ["La la la~", "Ehehe~"], 'Idle/Idle_Dance/Idle23_Dance03': ["Kyahaha~", "Watch me~"], 'Idle/Idle_Dance/Idle24_Dance04': ["Un un un~", "Ufufu~"],
  'Idle/Idle19_ShyRefusal': ["Wait, wait!", "No no no."], 'Idle/Idle93_Shush2': ["Shh."], 'Idle/Idle92_Shush1': ["Shhh…"], 'Idle/Idle27_Angry': ["Mou! Now I'm mad.", "Baka!"], 'Idle/Idle37_Tsundere': ["Hmph. I don't care.", "It's not like I was worried…"],
  'Idle/Idle67_FeelDown': ["Sonnaa…", "Haa…"], 'Idle/Idle29_Surprised': ["Ehh?!", "No way…"], 'Idle/Idle68_Surprise': ["Oh!", "Ah!"], 'Idle/Idle69_Surprise2': ["Eh?!", "Giku!"],
  'Idle/Idle99_Sleepy': ["Fuwaaa… sleepy…", "Munya…"], 'Idle/Idle05_Stretch': ["Nnn… stretch~", "Fuwaa~"], 'Idle/Idle30_Stretch2': ["Ahh~"], 'Idle/Idle100_BathroomUrgent': ["Uh oh… this might be bad…", "Gege…"],
  'Idle/Idle44_GreetingBow': ["Konnichiwa~", "Nice to meet you."], 'Idle/Idle16_WaveHands': ["Yoho~!", "Hi hi!"], 'Idle/Idle52_Curtsy': ["Hajimemashite~", "Pleased to meet you."], 'Idle/Idle45_WaveHandSlightly': ["Yaa~", "Hi."],
  'Idle/Idle_Pair/Idle21_HighFive1_1': ["High five!", "Yo!"], 'Idle/Idle73_IdolPose': ["Kyaa, embarrassing~", "Ehehe~"], 'Idle/Idle88_DoublePeacePose': ["Peace peace~", "Ehehe."], 'Idle/Idle89_CheekPointPose': ["Ehehe~", "Cute, right?"],
  'Idle/Idle41_CuteShyPose': ["Ehehe…", "Ufufu…"], 'Idle/Idle18_Shy': ["Kyaa… don't look…", "Ehehe…"], 'Idle/Idle39_CuteArmUp': ["Ehehe~"], 'Idle/Idle35_FingerSnap': ["Yo!"], 'Idle/Idle65_ThumbsUp': ["That's the way!", "Thank you~"], 'Idle/Idle91_ThumbsUp': ["Thanks!", "Nice one."],
  'Idle/Idle75_Pointing': ["Oh!", "There!"], 'Idle/Idle76_MotivatedPose': ["Ganbare!", "Fure fure!"], 'Idle/Idle90_HandsOnHipsConfident': ["Hai hai~", "Leave it to me."], 'Idle/Idle09_Waiting': ["Mmm…"], 'Idle/Idle11_LookingBack': ["Are?", "Hm?"],
  'Idle/Idle03_LookAtHands': ["Hee~"], 'Idle/Idle04_LookAtFeet': ["Are?"], 'Idle/Idle12_LeaningForward': ["Mm? Hee~"], 'Idle/Idle71_CatPose': ["Nyaa~"], 'Idle/Idle95_Cold1': ["Brrr…"], 'Idle/Idle97_Hot1': ["Sooo hot…"],
  'Idle/Idle15_TieShoelaces': ["Mm."], 'Idle/Idle85_Sneeze1': ["Ah… ah… achoo!"], 'Idle/Idle20_TriplePose': ["Yo! Ei! Tou!"], 'Idle/Idle72_LeanForward': ["Hee~"],
  'Sleep/TransitionFromStandingPose/Sleep_Start': ["Oyasumi…", "Fuwaaa…"], 'Sleep/TransitionFromStandingPose/Sleep_End': ["Did you call?", "Mm… I'm up… I'm up."],
  'Idle/Idle_Sit/Idle53_Seiza_Start': ["Mm."], 'Idle/Idle_Sit/Idle46_SitFloor_Start': ["Yoisho~"], 'Idle/Idle_Sit/Idle10_Sit_Start': ["Yoisho."],
};
