// Builds the browser version of Yui for the website.
//
// The site runs the *same* renderer as the desktop app — the same walk cycle, the same drag and
// throw physics, the same spring bones. src/renderer.js already talks to Electron through a single
// `window.pet` bridge object and falls back to a stub when there is none, so the web build needs no
// fork of the renderer: web/yui-boot.js supplies a bridge that does the browser-shaped thing for
// each call, and this script bundles the renderer unchanged.
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const WEB = path.join(ROOT, 'web');
const WIN = process.platform === 'win32';

fs.mkdirSync(path.join(WEB, 'assets'), { recursive: true });

// ---- her stylesheet, lifted from the app and adapted to sit over a scrolling page -------------
const appHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const style = appHtml.slice(appHtml.indexOf('<style>') + 7, appHtml.indexOf('</style>'));

// The app owns its whole window; the website does not. Drop the rules that would take the page
// over, and pin what is left to the viewport instead of the document.
const petCss = style
  .split('\n')
  .filter((l) => !/^\s*html,\s*body\s*\{/.test(l) && !/^\s*body\s*\{\s*user-select/.test(l))
  .join('\n')
  .replace(
    /\n\s*canvas \{[^}]*\}/,
    `
  /* A viewport-sized, clipped stage for her two canvases (body and effects). Fixed, so she stays
     on screen as the page scrolls; clipped, so the part of her canvas that hangs past a narrow
     window cannot turn into horizontal page scroll. */
  #yui-stage { position: fixed; inset: 0; overflow: hidden; z-index: 40; pointer-events: none; }
  #yui-stage canvas { display: block; position: absolute; left: 0; top: 0; pointer-events: none; }
  /* before the stage adopts them (one frame at startup) */
  body > canvas { display: block; position: fixed; left: 0; top: 0; z-index: 40; pointer-events: none; }`
  )
  // Everything she shows — bubble, panel, tour — must stack above her stage (40). The renderer
  // makes her canvas catch the mouse whenever the cursor is over the panel or the tour card (that
  // is how the app window stops being click-through there), and her canvas is 2.2x her height:
  // left below the card in z-order it would sit on top of the card's inputs and take every click
  // meant for them — as a grab. Same order as the app (tour above panel above bubble), lifted.
  .replace('#loading, #bubble { z-index: 5; }', '#loading, #bubble { z-index: 45; }')
  .replace('#panel { z-index: 10; }', '#panel { z-index: 50; }')
  .replace('#tour { z-index: 11; }', '#tour { z-index: 55; }')
  // Each rule block starts at the beginning of its own line; anchoring there keeps the swap inside
  // that block (the one-line z-index rules above also start with the same selector).
  .replace(/(\n  #loading \{[^}]*?)position: absolute;/, '$1position: fixed;')
  .replace(/(\n  #bubble \{[^}]*?)position: absolute;/, '$1position: fixed;')
  .replace(/(\n  #panel \{[^}]*?)position: absolute;/, '$1position: fixed;')
  .replace(/(\n  #tour \{[^}]*?)position: absolute;/, '$1position: fixed;');
// The swaps above are by shape; a stylesheet change in index.html must fail the build, not ship
// a card that sits under her canvas or scrolls with the page.
for (const sel of ['#tour { z-index: 55; }', '#panel { z-index: 50; }']) {
  if (!petCss.includes(sel)) throw new Error('index.html stylesheet changed shape: ' + sel + ' was not produced — update the replacements above');
}
for (const id of ['#loading', '#bubble', '#panel', '#tour']) {
  const m = petCss.match(new RegExp('\\n  ' + id + ' \\{[^}]*?position: (\\w+);'));
  if (!m || m[1] !== 'fixed') throw new Error('index.html stylesheet changed shape: ' + id + ' is not position: fixed after the swap');
}

fs.writeFileSync(path.join(WEB, 'pet.css'),
  '/* Generated by scripts/build-web.js from index.html — do not edit by hand. */\n' + petCss.trim() + `

/* ---- website-only additions --------------------------------------------------------------- */
/* Her panel is the app's, unchanged. The few controls that only mean something on a desktop —
   always-on-top, the sounds folder, Quit — are tagged .web-hide by the enhancer in yui-boot.js,
   which rewrites the panel for a browser each time the renderer redraws it. */
#panel .web-hide { display: none !important; }

/* ---- a phone ---------------------------------------------------------------------------------
   Everything she shows is placed beside her by the renderer, which is right on a monitor and
   wrong on a screen narrower than she is: the card lands on top of her. On a phone her things
   become sheets instead — the tour card under the header, her settings along the bottom — and
   the inline positions the renderer writes each frame are overridden. */
@media (max-width: 760px) {
  #tour {
    left: 10px !important; right: 10px !important; top: 74px !important; bottom: auto !important;
    width: auto !important; max-width: none; padding: 14px 16px 12px;
  }
  #tour .tail { display: none; }
  #tour h3 { font-size: 17px; }
  #tour p { font-size: 13px; }
  /* Her settings sit at the top of the screen, under the site's header — she stands at the
     bottom, and a sheet over her is a sheet over the thing you are changing. */
  #panel {
    left: 8px !important; right: 8px !important; top: 72px !important; bottom: auto !important;
    width: auto !important; max-height: 46vh;
  }
  /* With the panel up, her card moves down to just above her head so the two never stack. */
  html.yui-panel #tour {
    top: auto !important; bottom: calc(var(--yui-band, 320px) - 24px) !important;
  }
  #bubble { max-width: min(76vw, 280px); font-size: 14px; }
  /* the tour's own controls, thumb-sized */
  #tour button { padding: 11px 16px; font-size: 14px; }
  #tour input[type=text] { font-size: 16px; padding: 12px 14px; }   /* 16px: iOS does not zoom */
  #tour .demo { gap: 6px; }
  #tour .demo button { padding: 11px 4px; }
  #tour .actions { flex-wrap: wrap; row-gap: 8px; }
  #tour .dots { margin-left: 0; width: 100%; justify-content: center; }
  /* her panel's fields on a phone */
  #panel input[type=text], #panel select { font-size: 16px; }
  #panel .tabs button { padding: 10px 8px; }
}
/* A phone is narrower than her panel's fixed 336px. */
@media (max-width: 420px) { #panel { width: calc(100vw - 24px); } }

/* The relay address and token are for someone running their own feed; on a website they are noise
   in front of the one field that matters, so they fold away behind a disclosure. */
#panel .web-adv {
  display: block; width: 100%; text-align: left; background: transparent; color: var(--faint); box-shadow: none;
  font-size: 11px; font-weight: 600; letter-spacing: .04em; text-transform: uppercase;
  padding: 4px 0 8px; cursor: pointer;
}
#panel .web-adv:hover { color: var(--dim); filter: none; }
#panel .web-adv::before { content: "▸ "; }
#panel .web-adv.open::before { content: "▾ "; }

/* An explanation in her own panel, where a browser makes a field behave differently to the app. */
#panel .web-note {
  font-size: 11.5px; line-height: 1.5; color: var(--dim); text-transform: none; letter-spacing: 0;
  background: rgba(255,255,255,.04); border: 1px solid var(--line); border-radius: 10px;
  padding: 9px 11px; margin: 0 0 11px;
}
#panel .web-note.warn { color: var(--warn); background: rgba(232,187,85,.08); border-color: rgba(232,187,85,.25); }
#panel .web-note a { color: var(--accent); }
#panel .web-note b { color: var(--txt); font-weight: 650; }

#bubble { font-size: 15px; }
#yui-stage canvas { touch-action: none; }
/* While she is in hand the cursor sweeps across a page full of text; without this it leaves a
   trail of blue selection behind her. */
html.yui-grabbing, html.yui-grabbing body { user-select: none; -webkit-user-select: none; cursor: grabbing; }
`);
console.log('[web] pet.css written from the app stylesheet');

// ---- the renderer itself, unchanged ----------------------------------------------------------
// On Windows node_modules/esbuild/bin/esbuild is a JS shim (run it with node, not a .cmd through
// a shell); everywhere else it is the native binary itself.
const esbuildBin = path.join(ROOT, 'node_modules', 'esbuild', 'bin', 'esbuild');
const esbuildArgs = ['src/renderer.js', '--bundle', '--format=iife', '--outfile=web/yui-web.js',
  '--minify', '--target=chrome110,firefox110,safari16'];
if (WIN) execFileSync(process.execPath, [esbuildBin, ...esbuildArgs], { cwd: ROOT, stdio: 'inherit' });
else execFileSync(esbuildBin, esbuildArgs, { cwd: ROOT, stdio: 'inherit' });
console.log('[web] yui-web.js bundled');

// ---- her body ---------------------------------------------------------------------------------
// The VRM carries a 2.5 MB preview thumbnail that nothing on a web page ever shows; the copy the
// browser downloads goes without it (a GLB rewrite: same JSON, the BIN chunk re-packed minus that
// image's bytes, every later bufferView re-offset). A gzip twin sits beside it for the server to
// hand out as Content-Encoding: gzip — the mesh and skin data compress, the PNGs do not, but the
// download still comes out a fifth smaller.
const zlib = require('zlib');
function stripThumbnail(buf) {
  const jsonLen = buf.readUInt32LE(12);
  const json = JSON.parse(buf.slice(20, 20 + jsonLen).toString('utf8'));
  const binStart = 20 + jsonLen + 8;
  const bin = buf.slice(binStart, binStart + buf.readUInt32LE(20 + jsonLen));
  const meta0 = json.extensions && json.extensions.VRM && json.extensions.VRM.meta;
  const meta1 = json.extensions && json.extensions.VRMC_vrm && json.extensions.VRMC_vrm.meta;
  const thumbTex = meta0 && typeof meta0.texture === 'number' ? meta0.texture : null;
  const thumbImg = meta1 && typeof meta1.thumbnailImage === 'number' ? meta1.thumbnailImage
    : thumbTex != null && json.textures[thumbTex] ? json.textures[thumbTex].source : null;
  const byName = (json.images || []).findIndex((im) => /thumbnail/i.test(im.name || ''));
  const img = thumbImg != null ? thumbImg : byName;
  if (img < 0 || !json.images[img] || json.images[img].bufferView == null) return { buf, saved: 0 };
  // is that image used by any material? then it is not just a preview and stays
  const src = json.images[img];
  const usedBy = (json.textures || []).map((t, i) => (t.source === img ? i : -1)).filter((i) => i >= 0);
  const inMaterial = JSON.stringify(json.materials || []).match(/"index":(\d+)/g) || [];
  if (usedBy.some((ti) => inMaterial.includes('"index":' + ti))) return { buf, saved: 0 };
  const dropBv = src.bufferView;
  // re-pack the BIN without that view
  const views = json.bufferViews;
  const parts = []; let offset = 0;
  const newIndex = new Map();
  views.forEach((bv, i) => {
    if (i === dropBv) return;
    const data = bin.slice(bv.byteOffset || 0, (bv.byteOffset || 0) + bv.byteLength);
    const pad = (4 - (offset % 4)) % 4; if (pad) { parts.push(Buffer.alloc(pad)); offset += pad; }
    newIndex.set(i, { ...bv, byteOffset: offset });
    parts.push(data); offset += data.length;
  });
  const newViews = []; const remap = new Map();
  views.forEach((bv, i) => { if (i !== dropBv) { remap.set(i, newViews.length); newViews.push(newIndex.get(i)); } });
  const fix = (o) => { if (o && typeof o.bufferView === 'number') o.bufferView = remap.get(o.bufferView); };
  (json.accessors || []).forEach((a) => { fix(a); if (a.sparse) { fix(a.sparse.indices); fix(a.sparse.values); } });
  (json.images || []).forEach(fix);
  json.bufferViews = newViews;
  json.buffers[0].byteLength = offset;
  // the image itself: keep the slot (indices elsewhere stay valid) but point it at nothing
  json.images[img] = { name: src.name, mimeType: src.mimeType, uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=' };
  const newBin = Buffer.concat(parts);
  let jsonBuf = Buffer.from(JSON.stringify(json), 'utf8');
  const jpad = (4 - (jsonBuf.length % 4)) % 4; if (jpad) jsonBuf = Buffer.concat([jsonBuf, Buffer.alloc(jpad, 0x20)]);
  const header = Buffer.alloc(12); header.writeUInt32LE(0x46546C67, 0); header.writeUInt32LE(2, 4);
  const jh = Buffer.alloc(8); jh.writeUInt32LE(jsonBuf.length, 0); jh.writeUInt32LE(0x4E4F534A, 4);
  const bh = Buffer.alloc(8); bh.writeUInt32LE(newBin.length, 0); bh.writeUInt32LE(0x004E4942, 4);
  const out = Buffer.concat([header, jh, jsonBuf, bh, newBin]);
  out.writeUInt32LE(out.length, 8);
  return { buf: out, saved: buf.length - out.length };
}
const vrm = path.join(ROOT, 'models', 'shino.vrm');
const out = path.join(WEB, 'assets', 'yui.vrm');
// rebuilt when the model changes *or* when this script does — the stripping happens here, so a
// change to it must not leave a stale compressed copy behind
const vrmStamp = Math.max(fs.statSync(vrm).mtimeMs, fs.statSync(__filename).mtimeMs);
if (!fs.existsSync(out + '.gz') || vrmStamp > fs.statSync(out + '.gz').mtimeMs) {
  const { buf, saved } = stripThumbnail(fs.readFileSync(vrm));
  fs.writeFileSync(out, buf);
  fs.writeFileSync(out + '.gz', zlib.gzipSync(buf, { level: 9 }));
  console.log('[web] assets/yui.vrm written (' + (buf.length / 1048576).toFixed(1) + ' MB, thumbnail ' + (saved ? 'stripped: −' + (saved / 1048576).toFixed(1) + ' MB' : 'kept') + '; gzip ' + (fs.statSync(out + '.gz').size / 1048576).toFixed(1) + ' MB)');
}

// ---- her voice ---------------------------------------------------------------------------------
// The whole pack, not just the clips the default map references: her panel lets you pick any of
// them per event, exactly as the app does.
const mainJs = fs.readFileSync(path.join(ROOT, 'main.js'), 'utf8');
const block = mainJs.slice(mainJs.indexOf('const DEFAULT_SOUNDS'), mainJs.indexOf('let DEFAULT_RELAY_URL'));
const map = {};
for (const m of block.matchAll(/(\w+):\s*'file:([\w.-]+)'/g)) map[m[1]] = 'file:' + m[2];
const clips = fs.readdirSync(path.join(ROOT, 'sounds')).filter((f) => /\.(mp3|wav|ogg)$/i.test(f)).sort();
for (const v of Object.values(map)) if (!clips.includes(v.slice(5))) console.warn('[web] default sound not in sounds/: ' + v);

const soundDir = path.join(WEB, 'assets', 'sounds');
fs.mkdirSync(soundDir, { recursive: true });
for (const name of clips) fs.copyFileSync(path.join(ROOT, 'sounds', name), path.join(soundDir, name));
fs.writeFileSync(path.join(WEB, 'yui-sounds.js'),
  '// Generated by scripts/build-web.js. Her voice clips, as URLs the browser can load.\n' +
  'window.YUI_SOUNDS = ' + JSON.stringify({
    map,
    files: clips.map((n) => ({ name: n, url: 'assets/sounds/' + n })),
  }, null, 2) + ';\n');
console.log('[web] ' + clips.length + ' voice clips copied, yui-sounds.js written');

// ---- motion clips ------------------------------------------------------------------------------
// Converted humanoid clips (tools/clips/convert.mjs → clips/**.json, a symlink to the converted
// pack). Big JSON, so a gzip twin sits beside each for the server, like her body; only rebuilt
// when the clip is newer.
{
  const src = path.join(ROOT, 'clips'), dst = path.join(WEB, 'assets', 'clips');
  let n = 0, gz = 0;
  (function walk(rel) {
    const from = path.join(src, rel);
    if (!fs.existsSync(from)) return;
    for (const f of fs.readdirSync(from)) {
      const r = path.join(rel, f);
      if (fs.statSync(path.join(src, r)).isDirectory()) { walk(r); continue; }
      if (!/\.json$/.test(f)) continue;
      const a = path.join(src, r), b = path.join(dst, r);
      fs.mkdirSync(path.dirname(b), { recursive: true });
      const st = fs.statSync(a);
      if (!fs.existsSync(b) || fs.statSync(b).mtimeMs < st.mtimeMs) { fs.copyFileSync(a, b); fs.writeFileSync(b + '.gz', zlib.gzipSync(fs.readFileSync(a), { level: 6 })); gz++; }
      n++;
    }
  })('');
  console.log('[web] ' + n + ' motion clips in place (' + gz + ' rewritten)');
}

// ---- her defaults ------------------------------------------------------------------------------
// The website is meant to be the app, so it starts from the app's own defaultSettings() — read out
// of main.js at build time rather than copied, so the two cannot drift. main.js cannot be required
// here (it needs Electron), hence the text extraction. Anything the browser must do differently is
// applied on top in yui-boot.js, in one place, with its reason next to it.
const dm = mainJs.match(/function defaultSettings\(\) \{ return \{([\s\S]*?)\n\}; \}/);
if (!dm) throw new Error('main.js: defaultSettings() not found — the web build reads it by shape');
const appDefaults = new Function('DEFAULT_SOUNDS', 'DEFAULT_RELAY_TOKEN', 'return {' + dm[1] + '\n};')(map, '');
appDefaults.relayToken = '';   // never a token from this machine's relay.local.json in a public bundle
const stamp = new Date().toISOString().slice(0, 16).replace('T', ' ');
fs.writeFileSync(path.join(WEB, 'yui-defaults.js'),
  '// Generated by scripts/build-web.js from defaultSettings() in main.js — do not edit by hand.\n' +
  'window.YUI_DEFAULTS = ' + JSON.stringify(appDefaults, null, 2) + ';\n' +
  'window.YUI_BUILD = ' + JSON.stringify(stamp + ' web') + ';\n');
console.log('[web] yui-defaults.js written from main.js (' + Object.keys(appDefaults).length + ' keys)');

// ---- her tab icon, her fonts, her logo ---------------------------------------------------------
fs.copyFileSync(path.join(ROOT, 'yui.ico'), path.join(WEB, 'favicon.ico'));
fs.copyFileSync(path.join(ROOT, 'icon.png'), path.join(WEB, 'assets', 'icon.png'));
// the square portrait (with its background) is the social preview and the home-screen icon
fs.copyFileSync(path.join(ROOT, 'branding', 'yui-pfp.png'), path.join(WEB, 'assets', 'yui-pfp.png'));
// pet.css (from the app) and the pages both use Outfit + Rubik from fonts/, bundled with the app
fs.mkdirSync(path.join(WEB, 'fonts'), { recursive: true });
for (const f of fs.readdirSync(path.join(ROOT, 'fonts'))) if (/\.woff2$/.test(f)) fs.copyFileSync(path.join(ROOT, 'fonts', f), path.join(WEB, 'fonts', f));

// ---- the paper-trading page ----------------------------------------------------------------------
// Paperxiom's token page — Axiom's captured chrome, lightweight-charts, the mock world on the real
// bonding curve — copied in whole from the paper-axiom checkout and embedded on the front page, so
// a visitor can make a paper trade and watch her react to it exactly as she reacts to a real one.
// The copy is generated (git-ignored); web/trade/pa-yui.js, the bridge to her, is the source here.
// Without the checkout the build keeps whatever copy is already there.
const PA = process.env.PAPERXIOM_DIR || path.resolve(ROOT, '..', '..', 'EVERYTHING', 'paper-axiom');
const TRADE = path.join(WEB, 'trade');
if (fs.existsSync(path.join(PA, 'build', 'token.html'))) {
  const st = path.join(PA, 'frontend', 'static');
  const copyDir = (from, to) => { fs.mkdirSync(to, { recursive: true }); for (const f of fs.readdirSync(from)) {
    if (/\.bak/.test(f)) continue;
    const a = path.join(from, f), b = path.join(to, f);
    if (fs.statSync(a).isDirectory()) copyDir(a, b); else fs.copyFileSync(a, b);
  } };
  copyDir(st, path.join(TRADE, 'static'));
  // the page: its assets are next to it now, its home link is hers
  let html = fs.readFileSync(path.join(PA, 'build', 'token.html'), 'utf8');
  html = html.split('/static/').join('static/').replace('href="/"', 'href="../index.html"');
  html = html.replace('<script src="static/js/token.js"', '<script src="pa-yui.js"></script><script src="static/js/token.js"');
  // the captured page blurs and animates things the GPU then redoes behind a moving chart
  html = html.replace('</head>', '<style id="pa-lite">*,*::before,*::after{backdrop-filter:none!important;-webkit-backdrop-filter:none!important;animation-duration:0s!important;transition-duration:0s!important}</style></head>');
  // ?lesson=1 — Axiom's own nav and footer come off, so the starter's card can show just the
  // band that matters (token header, chart, buy ticket) by cropping rather than by rebuilding
  // the captured page's layout.
  html = html.replace('</head>', `<style id="pa-lesson">
html.pa-lesson .platform-app-shell > *:not(.platform-main-content){display:none!important}
html.pa-lesson,html.pa-lesson body{overflow:hidden!important}
</style></head>`);
  if (!html.includes('pa-yui.js')) throw new Error('token.html: could not place the bridge script');
  fs.writeFileSync(path.join(TRADE, 'token.html'), html);
  // the controller: the mint comes from the query, links stay inside the copy, the order function is reachable
  let tj = fs.readFileSync(path.join(st, 'js', 'token.js'), 'utf8');
  const edits = [
    ['const mint = decodeURIComponent((location.pathname.split("/")[2] || "")) || Mock.ROSTER[5].mint;',
     'const mint = new URLSearchParams(location.search).get("mint") || Mock.ROSTER[0].mint;'],
    ['if(a === "pulse") location.href = "/";', 'if(a === "pulse") return;'],
    ['location.href = "/token/" + m;', 'location.href = "?mint=" + m;'],
    ['location.href = "/token/" + r.mint;', 'location.href = "?mint=" + r.mint;'],
    ['TR.setSide = setSide;', 'TR.setSide = setSide; window.__paTrade = { order, TR, play(v){ PLAY = !!v; T0 = performance.now(); }, playing(){ return PLAY; }, clock(){ return CLOCK; }, stopAt(ms){ STOPAT = +ms || 0; }, seek, tape(){ return T; }, lesson };'],
    ['  /* ── boot ── */', `  function lesson(){ document.documentElement.classList.add("pa-lesson"); window.dispatchEvent(new Event("resize")); setTimeout(() => { window.dispatchEvent(new Event("resize")); if(CH) CH.frame(); }, 80); }

  /* ── boot ── */`],
    ['    bindChart();', '    bindChart();\n    if(q.get("lesson") === "1") setTimeout(lesson, 120);'],
    // a stop mark: playback pauses itself exactly there (the guided trade's "top")
    ['let SIDE = "buy", AMT = 0.5, PCT = 100,', 'let STOPAT = 0; let SIDE = "buy", AMT = 0.5, PCT = 100,'],
    ['if(PLAY){ CLOCK += dt * SPEED; let fed = 0;', 'if(PLAY){ CLOCK += dt * SPEED; if(STOPAT > 0 && CLOCK >= STOPAT){ CLOCK = STOPAT; PLAY = false; STOPAT = 0; } let fed = 0;'],
    // ?paused=1 opens the page frozen where ?at= put it; the replay transport only with ?rmt=1
    ['seek(start); PLAY = true;', 'seek(start); PLAY = q.get("paused") !== "1";'],
    ['function rmtInit(){', 'function rmtInit(){ if(q.get("rmt") !== "1") return;'],
    // the tape list is repainted at most a few times a second while prints stream in (it was every tick)
    ['let STOPAT = 0;', 'let STOPAT = 0, LASTTAPE = 0;'],
    ['if(fed){ tapePaint(); if(CH) CH.setMarkers(MARKS); }\n      if(IDX >= T.t.length){ PLAY = false; }\n      paintAll(fed > 0); }',
     'if(fed && now - LASTTAPE > 200){ LASTTAPE = now; tapePaint(); if(CH) CH.setMarkers(MARKS); }\n      if(IDX >= T.t.length){ PLAY = false; tapePaint(); if(CH) CH.setMarkers(MARKS); }\n      paintAll(false); }'],
  ];
  for (const [a, b] of edits) { if (!tj.includes(a)) throw new Error('token.js changed shape: ' + a.slice(0, 50)); tj = tj.replace(a, b); }
  fs.writeFileSync(path.join(TRADE, 'static', 'js', 'token.js'), tj);
  // the mock world: her own coin at the top of the roster, so the embed opens on $YUI
  let mj = fs.readFileSync(path.join(st, 'js', 'mock.js'), 'utf8');
  const namesAt = 'const NAMES = [\n';
  if (!mj.includes(namesAt)) throw new Error('mock.js changed shape: NAMES');
  mj = mj.replace(namesAt, namesAt + '    ["YUI","Yui, the Trading Companion"],\n');
  fs.writeFileSync(path.join(TRADE, 'static', 'js', 'mock.js'), mj);
  console.log('[web] trade/ copied from ' + PA + ' (' + (fs.statSync(path.join(TRADE, 'token.html')).size / 1048576).toFixed(1) + ' MB page)');
} else if (fs.existsSync(path.join(TRADE, 'token.html'))) {
  console.log('[web] trade/ kept as is (no paper-axiom checkout at ' + PA + ')');
} else {
  console.warn('[web] no paper-axiom checkout at ' + PA + ' — the paper-trading section will 404; set PAPERXIOM_DIR');
}

// ---- the download ------------------------------------------------------------------------------
// If a release has been built, drop it where the page links to, so web/ is a complete upload.
const rel = path.join(ROOT, 'release');
const zip = fs.existsSync(rel) && fs.readdirSync(rel).find((f) => /^Yui-.*\.zip$/.test(f));
if (zip) {
  const dlDir = path.join(WEB, 'downloads');
  fs.mkdirSync(dlDir, { recursive: true });
  const dst = path.join(dlDir, zip);
  if (!fs.existsSync(dst) || fs.statSync(path.join(rel, zip)).size !== fs.statSync(dst).size) {
    fs.copyFileSync(path.join(rel, zip), dst);
    console.log('[web] downloads/' + zip + ' copied (' + (fs.statSync(dst).size / 1048576).toFixed(1) + ' MB)');
  } else {
    console.log('[web] downloads/' + zip + ' already current');
  }
} else {
  console.log('[web] no release zip yet — run `npm run package` first, or host the download elsewhere');
}

const size = (f) => (fs.statSync(path.join(WEB, f)).size / 1024).toFixed(0) + ' KB';
console.log('[web] done — yui-web.js ' + size('yui-web.js') + ', pet.css ' + size('pet.css'));
