// Builds the browser version of Yui for the website.
//
// The site runs the *same* renderer as the desktop app — the same walk cycle, the same drag and
// throw physics, the same spring bones. src/renderer.js already talks to Electron through a single
// `window.pet` bridge object and falls back to a stub when there is none, so the web build needs no
// fork of the renderer: web/yui-boot.js supplies a bridge that does the browser-shaped thing for
// each call, and this script bundles the renderer unchanged.
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const WEB = path.join(ROOT, 'web');
const WIN = process.platform === 'win32';

fs.mkdirSync(path.join(WEB, 'assets'), { recursive: true });

// ---- her stylesheet, lifted from the app and adapted to sit over a scrolling page -------------
const appHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const style = appHtml.slice(appHtml.indexOf('<style>') + 7, appHtml.indexOf('</style>'));

// The app owns its whole window; the website does not. Drop the rules that would take the page
// over, and pin what is left to the viewport instead of the document.
const petCss = style
  .split('\n')
  .filter((l) => !/^\s*html,\s*body\s*\{/.test(l) && !/^\s*body\s*\{\s*user-select/.test(l))
  .join('\n')
  .replace(
    /\n\s*canvas \{[^}]*\}/,
    `
  /* A viewport-sized, clipped stage for her two canvases (body and effects). Fixed, so she stays
     on screen as the page scrolls; clipped, so the part of her canvas that hangs past a narrow
     window cannot turn into horizontal page scroll. */
  #yui-stage { position: fixed; inset: 0; overflow: hidden; z-index: 40; pointer-events: none; }
  #yui-stage canvas { display: block; position: absolute; left: 0; top: 0; pointer-events: none; }
  /* before the stage adopts them (one frame at startup) */
  body > canvas { display: block; position: fixed; left: 0; top: 0; z-index: 40; pointer-events: none; }`
  )
  .replace('#loading, #bubble { z-index: 5; }', '#loading, #bubble { z-index: 45; }')
  .replace('#panel { z-index: 10; }', '#panel { z-index: 50; }')
  .replace(/#loading \{\s*\n\s*position: absolute;/, '#loading {\n    position: fixed;')
  .replace(/#bubble \{\s*\n\s*position: absolute;/, '#bubble {\n    position: fixed;')
  .replace(/(#panel \{[\s\S]*?)position: absolute;/, '$1position: fixed;');

fs.writeFileSync(path.join(WEB, 'pet.css'),
  '/* Generated by scripts/build-web.js from index.html — do not edit by hand. */\n' + petCss.trim() + `

/* ---- website-only additions --------------------------------------------------------------- */
/* Her panel is the app's, unchanged. The few controls that only mean something on a desktop —
   always-on-top, the sounds folder, Quit — are tagged .web-hide by the enhancer in yui-boot.js,
   which rewrites the panel for a browser each time the renderer redraws it. */
#panel .web-hide { display: none !important; }

/* A phone is narrower than her panel's fixed 336px. */
@media (max-width: 420px) { #panel { width: calc(100vw - 24px); } }

/* The relay address and token are for someone running their own feed; on a website they are noise
   in front of the one field that matters, so they fold away behind a disclosure. */
#panel .web-adv {
  display: block; width: 100%; text-align: left; background: transparent; color: var(--faint); box-shadow: none;
  font-size: 11px; font-weight: 600; letter-spacing: .04em; text-transform: uppercase;
  padding: 4px 0 8px; cursor: pointer;
}
#panel .web-adv:hover { color: var(--dim); filter: none; }
#panel .web-adv::before { content: "▸ "; }
#panel .web-adv.open::before { content: "▾ "; }

/* An explanation in her own panel, where a browser makes a field behave differently to the app. */
#panel .web-note {
  font-size: 11.5px; line-height: 1.5; color: var(--dim); text-transform: none; letter-spacing: 0;
  background: rgba(255,255,255,.04); border: 1px solid var(--line); border-radius: 10px;
  padding: 9px 11px; margin: 0 0 11px;
}
#panel .web-note.warn { color: var(--warn); background: rgba(232,187,85,.08); border-color: rgba(232,187,85,.25); }
#panel .web-note a { color: var(--accent); }
#panel .web-note b { color: var(--txt); font-weight: 650; }

#bubble { font-size: 15px; }
#yui-stage canvas { touch-action: none; }
/* While she is in hand the cursor sweeps across a page full of text; without this it leaves a
   trail of blue selection behind her. */
html.yui-grabbing, html.yui-grabbing body { user-select: none; -webkit-user-select: none; cursor: grabbing; }
`);
console.log('[web] pet.css written from the app stylesheet');

// ---- the renderer itself, unchanged ----------------------------------------------------------
// the shim is plain JS: run it with node, rather than a .cmd through a shell
execFileSync(process.execPath,
  [path.join(ROOT, 'node_modules', 'esbuild', 'bin', 'esbuild'),
    'src/renderer.js', '--bundle', '--format=iife', '--outfile=web/yui-web.js',
    '--minify', '--target=chrome110,firefox110,safari16'],
  { cwd: ROOT, stdio: 'inherit' });
console.log('[web] yui-web.js bundled');

// ---- her body ---------------------------------------------------------------------------------
const vrm = path.join(ROOT, 'models', 'shino.vrm');
const out = path.join(WEB, 'assets', 'yui.vrm');
if (!fs.existsSync(out) || fs.statSync(vrm).mtimeMs > fs.statSync(out).mtimeMs) {
  fs.copyFileSync(vrm, out);
  console.log('[web] assets/yui.vrm copied (' + (fs.statSync(out).size / 1048576).toFixed(1) + ' MB)');
}

// ---- her voice ---------------------------------------------------------------------------------
// Only the clips the default sound map actually references, not the whole 47-file pack.
const mainJs = fs.readFileSync(path.join(ROOT, 'main.js'), 'utf8');
const block = mainJs.slice(mainJs.indexOf('const DEFAULT_SOUNDS'), mainJs.indexOf('let DEFAULT_RELAY_URL'));
const map = {};
for (const m of block.matchAll(/(\w+):\s*'file:([\w.-]+)'/g)) map[m[1]] = 'file:' + m[2];
const wanted = [...new Set(Object.values(map).map((v) => v.slice(5)))];

const soundDir = path.join(WEB, 'assets', 'sounds');
fs.mkdirSync(soundDir, { recursive: true });
let copiedSounds = 0;
for (const name of wanted) {
  const src = path.join(ROOT, 'sounds', name);
  if (!fs.existsSync(src)) { console.warn('[web] missing sound ' + name); continue; }
  fs.copyFileSync(src, path.join(soundDir, name));
  copiedSounds++;
}
fs.writeFileSync(path.join(WEB, 'yui-sounds.js'),
  '// Generated by scripts/build-web.js. Her voice clips, as URLs the browser can load.\n' +
  'window.YUI_SOUNDS = ' + JSON.stringify({
    map,
    files: wanted.map((n) => ({ name: n, url: 'assets/sounds/' + n })),
  }, null, 2) + ';\n');
console.log('[web] ' + copiedSounds + ' voice clips copied, yui-sounds.js written');

// ---- the download ------------------------------------------------------------------------------
// If a release has been built, drop it where the page links to, so web/ is a complete upload.
const rel = path.join(ROOT, 'release');
const zip = fs.existsSync(rel) && fs.readdirSync(rel).find((f) => /^Yui-.*\.zip$/.test(f));
if (zip) {
  const dlDir = path.join(WEB, 'downloads');
  fs.mkdirSync(dlDir, { recursive: true });
  const dst = path.join(dlDir, zip);
  if (!fs.existsSync(dst) || fs.statSync(path.join(rel, zip)).size !== fs.statSync(dst).size) {
    fs.copyFileSync(path.join(rel, zip), dst);
    console.log('[web] downloads/' + zip + ' copied (' + (fs.statSync(dst).size / 1048576).toFixed(1) + ' MB)');
  } else {
    console.log('[web] downloads/' + zip + ' already current');
  }
} else {
  console.log('[web] no release zip yet — run `npm run package` first, or host the download elsewhere');
}

const size = (f) => (fs.statSync(path.join(WEB, f)).size / 1024).toFixed(0) + ' KB';
console.log('[web] done — yui-web.js ' + size('yui-web.js') + ', pet.css ' + size('pet.css'));
