// Generated by tools/voice-pack/gen.mjs — do not edit. Lines live in tools/voice-pack/lines.mjs.
export const VOICE_PACK = {
 "voiceId": "ocZQ262SsZb9RIxcQBOj",
 "model": "eleven_v3",
 "events": {
  "greet": [
   "file:yui-greet-1.mp3",
   "file:yui-greet-2.mp3",
   "file:yui-greet-3.mp3",
   "file:yui-greet-4.mp3",
   "file:yui-greet-5.mp3",
   "file:yui-greet-6.mp3",
   "file:yui-greet-7.mp3",
   "file:yui-greet-8.mp3"
  ],
  "connect": [
   "file:yui-connect-1.mp3",
   "file:yui-connect-2.mp3",
   "file:yui-connect-3.mp3",
   "file:yui-connect-4.mp3"
  ],
  "buy": [
   "file:yui-buy-1.mp3",
   "file:yui-buy-2.mp3",
   "file:yui-buy-3.mp3",
   "file:yui-buy-4.mp3",
   "file:yui-buy-5.mp3",
   "file:yui-buy-6.mp3",
   "file:yui-buy-7.mp3",
   "file:yui-buy-8.mp3",
   "file:yui-buy-9.mp3",
   "file:yui-buy-10.mp3"
  ],
  "bigBuy": [
   "file:yui-bigBuy-1.mp3",
   "file:yui-bigBuy-2.mp3",
   "file:yui-bigBuy-3.mp3",
   "file:yui-bigBuy-4.mp3",
   "file:yui-bigBuy-5.mp3",
   "file:yui-bigBuy-6.mp3"
  ],
  "sellFlat": [
   "file:yui-sellFlat-1.mp3",
   "file:yui-sellFlat-2.mp3",
   "file:yui-sellFlat-3.mp3",
   "file:yui-sellFlat-4.mp3",
   "file:yui-sellFlat-5.mp3",
   "file:yui-sellFlat-6.mp3"
  ],
  "profit": [
   "file:yui-profit-1.mp3",
   "file:yui-profit-2.mp3",
   "file:yui-profit-3.mp3",
   "file:yui-profit-4.mp3",
   "file:yui-profit-5.mp3",
   "file:yui-profit-6.mp3",
   "file:yui-profit-7.mp3",
   "file:yui-profit-8.mp3",
   "file:yui-profit-9.mp3",
   "file:yui-profit-10.mp3",
   "file:yui-profit-11.mp3",
   "file:yui-profit-12.mp3"
  ],
  "bigProfit": [
   "file:yui-bigProfit-1.mp3",
   "file:yui-bigProfit-2.mp3",
   "file:yui-bigProfit-3.mp3",
   "file:yui-bigProfit-4.mp3",
   "file:yui-bigProfit-5.mp3",
   "file:yui-bigProfit-6.mp3",
   "file:yui-bigProfit-7.mp3",
   "file:yui-bigProfit-8.mp3"
  ],
  "loss": [
   "file:yui-loss-1.mp3",
   "file:yui-loss-2.mp3",
   "file:yui-loss-3.mp3",
   "file:yui-loss-4.mp3",
   "file:yui-loss-5.mp3",
   "file:yui-loss-6.mp3",
   "file:yui-loss-7.mp3",
   "file:yui-loss-8.mp3",
   "file:yui-loss-9.mp3",
   "file:yui-loss-10.mp3"
  ],
  "bigLoss": [
   "file:yui-bigLoss-1.mp3",
   "file:yui-bigLoss-2.mp3",
   "file:yui-bigLoss-3.mp3",
   "file:yui-bigLoss-4.mp3",
   "file:yui-bigLoss-5.mp3",
   "file:yui-bigLoss-6.mp3",
   "file:yui-bigLoss-7.mp3",
   "file:yui-bigLoss-8.mp3"
  ],
  "guard": [
   "file:yui-guard-1.mp3",
   "file:yui-guard-2.mp3",
   "file:yui-guard-3.mp3",
   "file:yui-guard-4.mp3",
   "file:yui-guard-5.mp3",
   "file:yui-guard-6.mp3"
  ],
  "milestone": [
   "file:yui-milestone-1.mp3",
   "file:yui-milestone-2.mp3",
   "file:yui-milestone-3.mp3",
   "file:yui-milestone-4.mp3",
   "file:yui-milestone-5.mp3"
  ],
  "cheerUp": [
   "file:yui-cheerUp-1.mp3",
   "file:yui-cheerUp-2.mp3",
   "file:yui-cheerUp-3.mp3",
   "file:yui-cheerUp-4.mp3",
   "file:yui-cheerUp-5.mp3"
  ],
  "grab": [
   "file:yui-grab-1.mp3",
   "file:yui-grab-2.mp3",
   "file:yui-grab-3.mp3",
   "file:yui-grab-4.mp3",
   "file:yui-grab-5.mp3"
  ],
  "throw": [
   "file:yui-throw-1.mp3",
   "file:yui-throw-2.mp3",
   "file:yui-throw-3.mp3",
   "file:yui-throw-4.mp3"
  ],
  "land": [
   "file:yui-land-1.mp3",
   "file:yui-land-2.mp3",
   "file:yui-land-3.mp3",
   "file:yui-land-4.mp3"
  ],
  "dizzy": [
   "file:yui-dizzy-1.mp3",
   "file:yui-dizzy-2.mp3",
   "file:yui-dizzy-3.mp3"
  ],
  "jump": [
   "file:yui-jump-1.mp3",
   "file:yui-jump-2.mp3",
   "file:yui-jump-3.mp3"
  ],
  "stretch": [
   "file:yui-stretch-1.mp3",
   "file:yui-stretch-2.mp3",
   "file:yui-stretch-3.mp3"
  ],
  "hover": [
   "file:yui-hover-1.mp3",
   "file:yui-hover-2.mp3",
   "file:yui-hover-3.mp3",
   "file:yui-hover-4.mp3"
  ],
  "click": [
   "file:yui-click-1.mp3",
   "file:yui-click-2.mp3",
   "file:yui-click-3.mp3",
   "file:yui-click-4.mp3"
  ],
  "sleep": [
   "file:yui-sleep-1.mp3",
   "file:yui-sleep-2.mp3",
   "file:yui-sleep-3.mp3"
  ],
  "wake": [
   "file:yui-wake-1.mp3",
   "file:yui-wake-2.mp3",
   "file:yui-wake-3.mp3",
   "file:yui-wake-4.mp3"
  ],
  "scorecard": [
   "file:yui-scorecard-1.mp3",
   "file:yui-scorecard-2.mp3",
   "file:yui-scorecard-3.mp3"
  ]
 },
 "clips": {
  "Idle/Idle08_ComeUpWithAnIdea": [
   "file:yui-idle08-comeupwithanidea-1.mp3",
   "file:yui-idle08-comeupwithanidea-2.mp3"
  ],
  "Idle/Idle17_StumbleAndFall": [
   "file:yui-idle17-stumbleandfall-1.mp3",
   "file:yui-idle17-stumbleandfall-2.mp3"
  ],
  "Idle/Idle83_StumbleAndFall2": [
   "file:yui-idle83-stumbleandfall2-1.mp3",
   "file:yui-idle83-stumbleandfall2-2.mp3"
  ],
  "Idle/Idle84_StumbleAndFall3": [
   "file:yui-idle84-stumbleandfall3-1.mp3",
   "file:yui-idle84-stumbleandfall3-2.mp3"
  ],
  "Idle/Idle38_Cry": [
   "file:yui-idle38-cry-1.mp3",
   "file:yui-idle38-cry-2.mp3"
  ],
  "Combat/Combat_BareHands_Damage4": [
   "file:yui-combat-barehands-damage4-1.mp3",
   "file:yui-combat-barehands-damage4-2.mp3"
  ],
  "Combat/Combat_BareHands_DamageAll": [
   "file:yui-combat-barehands-damageall-1.mp3"
  ],
  "Idle/Idle36_Yay": [
   "file:yui-idle36-yay-1.mp3",
   "file:yui-idle36-yay-2.mp3"
  ],
  "Idle/Idle25_Cheers": [
   "file:yui-idle25-cheers-1.mp3",
   "file:yui-idle25-cheers-2.mp3"
  ],
  "Idle/Idle66_JumpForJoy": [
   "file:yui-idle66-jumpforjoy-1.mp3",
   "file:yui-idle66-jumpforjoy-2.mp3"
  ],
  "Idle/Idle74_Cheer": [
   "file:yui-idle74-cheer-1.mp3",
   "file:yui-idle74-cheer-2.mp3"
  ],
  "Idle/Idle28_Laugh": [
   "file:yui-idle28-laugh-1.mp3",
   "file:yui-idle28-laugh-2.mp3"
  ],
  "Idle/Idle26_Shout": [
   "file:yui-idle26-shout-1.mp3",
   "file:yui-idle26-shout-2.mp3"
  ],
  "Idle/Idle07_SpinningJump": [
   "file:yui-idle07-spinningjump-1.mp3",
   "file:yui-idle07-spinningjump-2.mp3"
  ],
  "Idle/Idle06_JumpAround": [
   "file:yui-idle06-jumparound-1.mp3",
   "file:yui-idle06-jumparound-2.mp3"
  ],
  "Idle/Idle54_CartwheelAndBackHandspring": [
   "file:yui-idle54-cartwheelandbackhandspring-1.mp3",
   "file:yui-idle54-cartwheelandbackhandspring-2.mp3"
  ],
  "Idle/Idle55_Backflip": [
   "file:yui-idle55-backflip-1.mp3",
   "file:yui-idle55-backflip-2.mp3"
  ],
  "Idle/Idle56_Handstand": [
   "file:yui-idle56-handstand-1.mp3",
   "file:yui-idle56-handstand-2.mp3"
  ],
  "Idle/Idle_Dance/Idle13_Dance01": [
   "file:yui-idle13-dance01-1.mp3",
   "file:yui-idle13-dance01-2.mp3"
  ],
  "Idle/Idle_Dance/Idle14_Dance02": [
   "file:yui-idle14-dance02-1.mp3",
   "file:yui-idle14-dance02-2.mp3"
  ],
  "Idle/Idle_Dance/Idle23_Dance03": [
   "file:yui-idle23-dance03-1.mp3",
   "file:yui-idle23-dance03-2.mp3"
  ],
  "Idle/Idle_Dance/Idle24_Dance04": [
   "file:yui-idle24-dance04-1.mp3",
   "file:yui-idle24-dance04-2.mp3"
  ],
  "Idle/Idle19_ShyRefusal": [
   "file:yui-idle19-shyrefusal-1.mp3",
   "file:yui-idle19-shyrefusal-2.mp3"
  ],
  "Idle/Idle93_Shush2": [
   "file:yui-idle93-shush2-1.mp3"
  ],
  "Idle/Idle92_Shush1": [
   "file:yui-idle92-shush1-1.mp3"
  ],
  "Idle/Idle27_Angry": [
   "file:yui-idle27-angry-1.mp3",
   "file:yui-idle27-angry-2.mp3"
  ],
  "Idle/Idle37_Tsundere": [
   "file:yui-idle37-tsundere-1.mp3",
   "file:yui-idle37-tsundere-2.mp3"
  ],
  "Idle/Idle67_FeelDown": [
   "file:yui-idle67-feeldown-1.mp3",
   "file:yui-idle67-feeldown-2.mp3"
  ],
  "Idle/Idle29_Surprised": [
   "file:yui-idle29-surprised-1.mp3",
   "file:yui-idle29-surprised-2.mp3"
  ],
  "Idle/Idle68_Surprise": [
   "file:yui-idle68-surprise-1.mp3",
   "file:yui-idle68-surprise-2.mp3"
  ],
  "Idle/Idle69_Surprise2": [
   "file:yui-idle69-surprise2-1.mp3",
   "file:yui-idle69-surprise2-2.mp3"
  ],
  "Idle/Idle99_Sleepy": [
   "file:yui-idle99-sleepy-1.mp3",
   "file:yui-idle99-sleepy-2.mp3"
  ],
  "Idle/Idle05_Stretch": [
   "file:yui-idle05-stretch-1.mp3",
   "file:yui-idle05-stretch-2.mp3"
  ],
  "Idle/Idle30_Stretch2": [
   "file:yui-idle30-stretch2-1.mp3"
  ],
  "Idle/Idle100_BathroomUrgent": [
   "file:yui-idle100-bathroomurgent-1.mp3",
   "file:yui-idle100-bathroomurgent-2.mp3"
  ],
  "Idle/Idle44_GreetingBow": [
   "file:yui-idle44-greetingbow-1.mp3",
   "file:yui-idle44-greetingbow-2.mp3"
  ],
  "Idle/Idle16_WaveHands": [
   "file:yui-idle16-wavehands-1.mp3",
   "file:yui-idle16-wavehands-2.mp3"
  ],
  "Idle/Idle52_Curtsy": [
   "file:yui-idle52-curtsy-1.mp3",
   "file:yui-idle52-curtsy-2.mp3"
  ],
  "Idle/Idle45_WaveHandSlightly": [
   "file:yui-idle45-wavehandslightly-1.mp3",
   "file:yui-idle45-wavehandslightly-2.mp3"
  ],
  "Idle/Idle_Pair/Idle21_HighFive1_1": [
   "file:yui-idle21-highfive1-1-1.mp3",
   "file:yui-idle21-highfive1-1-2.mp3"
  ],
  "Idle/Idle73_IdolPose": [
   "file:yui-idle73-idolpose-1.mp3",
   "file:yui-idle73-idolpose-2.mp3"
  ],
  "Idle/Idle88_DoublePeacePose": [
   "file:yui-idle88-doublepeacepose-1.mp3",
   "file:yui-idle88-doublepeacepose-2.mp3"
  ],
  "Idle/Idle89_CheekPointPose": [
   "file:yui-idle89-cheekpointpose-1.mp3",
   "file:yui-idle89-cheekpointpose-2.mp3"
  ],
  "Idle/Idle41_CuteShyPose": [
   "file:yui-idle41-cuteshypose-1.mp3",
   "file:yui-idle41-cuteshypose-2.mp3"
  ],
  "Idle/Idle18_Shy": [
   "file:yui-idle18-shy-1.mp3",
   "file:yui-idle18-shy-2.mp3"
  ],
  "Idle/Idle39_CuteArmUp": [
   "file:yui-idle39-cutearmup-1.mp3"
  ],
  "Idle/Idle35_FingerSnap": [
   "file:yui-idle35-fingersnap-1.mp3"
  ],
  "Idle/Idle65_ThumbsUp": [
   "file:yui-idle65-thumbsup-1.mp3",
   "file:yui-idle65-thumbsup-2.mp3"
  ],
  "Idle/Idle91_ThumbsUp": [
   "file:yui-idle91-thumbsup-1.mp3",
   "file:yui-idle91-thumbsup-2.mp3"
  ],
  "Idle/Idle75_Pointing": [
   "file:yui-idle75-pointing-1.mp3",
   "file:yui-idle75-pointing-2.mp3"
  ],
  "Idle/Idle76_MotivatedPose": [
   "file:yui-idle76-motivatedpose-1.mp3",
   "file:yui-idle76-motivatedpose-2.mp3"
  ],
  "Idle/Idle90_HandsOnHipsConfident": [
   "file:yui-idle90-handsonhipsconfident-1.mp3",
   "file:yui-idle90-handsonhipsconfident-2.mp3"
  ],
  "Idle/Idle09_Waiting": [
   "file:yui-idle09-waiting-1.mp3"
  ],
  "Idle/Idle11_LookingBack": [
   "file:yui-idle11-lookingback-1.mp3",
   "file:yui-idle11-lookingback-2.mp3"
  ],
  "Idle/Idle03_LookAtHands": [
   "file:yui-idle03-lookathands-1.mp3"
  ],
  "Idle/Idle04_LookAtFeet": [
   "file:yui-idle04-lookatfeet-1.mp3"
  ],
  "Idle/Idle12_LeaningForward": [
   "file:yui-idle12-leaningforward-1.mp3"
  ],
  "Idle/Idle71_CatPose": [
   "file:yui-idle71-catpose-1.mp3"
  ],
  "Idle/Idle95_Cold1": [
   "file:yui-idle95-cold1-1.mp3"
  ],
  "Idle/Idle97_Hot1": [
   "file:yui-idle97-hot1-1.mp3"
  ],
  "Idle/Idle15_TieShoelaces": [
   "file:yui-idle15-tieshoelaces-1.mp3"
  ],
  "Idle/Idle85_Sneeze1": [
   "file:yui-idle85-sneeze1-1.mp3"
  ],
  "Idle/Idle20_TriplePose": [
   "file:yui-idle20-triplepose-1.mp3"
  ],
  "Idle/Idle72_LeanForward": [
   "file:yui-idle72-leanforward-1.mp3"
  ],
  "Sleep/TransitionFromStandingPose/Sleep_Start": [
   "file:yui-sleep-start-1.mp3",
   "file:yui-sleep-start-2.mp3"
  ],
  "Sleep/TransitionFromStandingPose/Sleep_End": [
   "file:yui-sleep-end-1.mp3",
   "file:yui-sleep-end-2.mp3"
  ],
  "Idle/Idle_Sit/Idle53_Seiza_Start": [
   "file:yui-idle53-seiza-start-1.mp3"
  ],
  "Idle/Idle_Sit/Idle46_SitFloor_Start": [
   "file:yui-idle46-sitfloor-start-1.mp3"
  ],
  "Idle/Idle_Sit/Idle10_Sit_Start": [
   "file:yui-idle10-sit-start-1.mp3"
  ]
 }
};
